/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemasdistribuidos_produtorconsumidor.janelas;

import java.rmi.Naming;
import sistemasdistribuidos_produtorconsumidor.InterfaceRemota;

/**
 *
 * @author farofa
 */
public class Consumidor extends javax.swing.JFrame {
    private static InterfaceRemota server;
    
    /**
     * Creates new form Servidor
     */
    public Consumidor(String host, String endereco) {
        initComponents();
                                           
        try {
            server = (InterfaceRemota) Naming.lookup("rmi://"+host+"/"+endereco);
        } catch (Exception ex) {
            setLog("Mensagem:\n"+ex.getMessage(), true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoConsumir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consumidor");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consumidor"));

        botaoConsumir.setText("Consumir");
        botaoConsumir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConsumirActionPerformed(evt);
            }
        });
        jPanel1.add(botaoConsumir);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Logs"));

        textoLog.setEditable(false);
        textoLog.setColumns(20);
        textoLog.setLineWrap(true);
        textoLog.setRows(5);
        textoLog.setTabSize(0);
        textoLog.setFocusable(false);
        jScrollPane1.setViewportView(textoLog);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoConsumirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConsumirActionPerformed
        try {
            String msg = server.consome();
            setLog(msg, false);
        } catch (Exception e) {
            setLog("Mensagem:\n"+e.getMessage(), true);
        }
    }//GEN-LAST:event_botaoConsumirActionPerformed

    public void setLog(String msg, boolean erro)
    {
        if(!textoLog.getText().isEmpty())
            textoLog.append("\n\n");
        
        if(erro == true)
            textoLog.append("Erro:\n");
        
        textoLog.append(msg);
        textoLog.setCaretPosition(textoLog.getDocument().getLength());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConsumir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea textoLog;
    // End of variables declaration//GEN-END:variables
}
